name: Build full project
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install tools
              run: |
                curl -O https://developer.arm.com/-/media/Files/downloads/gnu/12.3.rel1/binrel/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi.tar.xz \
                && tar -xf arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi.tar.xz -C /opt \
                && echo "/opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin" >> $GITHUB_PATH
            - name: Checkout
              uses: actions/Checkout
            - name: Build
              run: |
                cmake . -B build --toolchain cmake\gcc-arm-none-eabi.cmake -DCMAKE_BUILD_TYPE=release




