name: Build
on: push
jobs:
  build_debug:
      runs-on: ubuntu-latest
      container: 
        image: ghcr.io/jensboe/arm-cortex-build:v1.3.0
      steps:
      - name: Checkout
        uses: actions/Checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: |
          cmake --preset gcc-arm 
          cmake --build build/gcc-arm
      - uses: actions/upload-artifact@v3
        if: 
        with:
          name: Debug
          path: |
            build/**/*.bin
            build/**/*.elf
            build/**/*.hex
            build/**/*.a
            build/**/*.map
            !build/CMakeFiles

