name: Build full project
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        container: 
          image: ghcr.io/jensboe/arm-cortex-build:v1.0.1
        steps:
        - name: Checkout
          uses: actions/Checkout@v4
          with:
            submodules: 'true'
        - name: Build
          run: |
            cmake -G Ninja -S . -B build --toolchain cmake/gcc-arm-none-eabi.cmake -DCMAKE_BUILD_TYPE=release 
            cmake --build build
        - uses: actions/upload-artifact@v3
          with:
            name: Core
            path: |
              build/**/*.bin
              build/**/*.elf
              build/**/*.hex
              build/**/*.a
              build/**/*.map


