name: Build full project
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        container: 
          image: ghcr.io/jensboe/arm-cortex-build:v1.0.0
        steps:
        - name: Checkout
          uses: actions/Checkout@v4
        - name: Build
          run: |
            cmake . -B build --toolchain cmake\gcc-arm-none-eabi.cmake -DCMAKE_BUILD_TYPE=release




