name: Test
on: push
jobs:
  test:
      runs-on: ubuntu-latest
      container: 
        image: ghcr.io/jensboe/arm-cortex-build:v1.3.0
      steps:
      - name: Checkout
        uses: actions/Checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: |
          cmake --preset win
          cmake --build build/gcc-arm
          cd build/gcc-arm
          ctest
